### ISSUE TITLE
Split output files

### ISSUE THREAD

**Issue by Swiip** [FountainJS/generator-fountain-webpack#4]
I made a first very naive version of optimization task for Webpack. It bundles everything inside `index-[hash].js` including vendors even styles.

It's enough at this point but we should (and it's possible) split output files.
- For vendors: https://webpack.github.io/docs/code-splitting.html
- For styles: https://webpack.github.io/docs/stylesheets.html

**Comment by zckrs** [comment]
Maybe use the conf defined by [Angular.io](https://angular.io/docs/ts/latest/guide/webpack.html)
