### ISSUE TITLE
webpackChangeHandler does not use correct errrorHandler

### ISSUE THREAD

**Issue by cwilsn** [FountainJS/generator-fountain-webpack#46]
webpackChangeHandler has

`conf.errorHandler('Webpack')(err);`

but conf is the webpack.conf not gulp.conf.

If gulp.conf is used, this.emit is not valid since `this` is the gulp.conf object.

**Comment by micaelmbagira** [comment]
Hi @pusherman thanks for reporting, this is a bug indeed

**Comment by cwilsn** [comment]
@micaelmbagira this is exactly what I tried locally but this caused another issue.

`this.emit` in the error handler is undefined because the error is coming from webpack and not a gulp stream.  Since it doesn't emit 'end' gulp just pauses without exiting.
