### ISSUE TITLE
Webpack 2.0 beta and tree shaking

### ISSUE THREAD

**Issue by scttcper** [FountainJS/generator-fountain-webpack#5]
Would be interested in seeing the generator be ready for webpack 2.x with the new features it brings. Example: http://www.2ality.com/2015/12/webpack-tree-shaking.html

Played around with it locally and it seems the .babelrc needs to be changed to match the article along with OccurenceOrderPlugin -> OccurrenceOrderPlugin because spelling mistake in legacy version.

Can send a pull request

**Comment by Swiip** [comment]
Yep! To be honest I was already thinking of switching to Webpack 2 globally for Fountain. It's still in heavy dev I think we can target using the next big version right now.

But I didn't found yet the time to investigate further.

**Comment by zckrs** [comment]
We use Webpack 2.x :)
